In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Breast_Cancer.csv')
df

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0      68  White        Married       T1      N1       IIA   
1      50  White        Married       T2      N2      IIIA   
2      58  White       Divorced       T3      N3      IIIC   
3      58  White        Married       T1      N1       IIA   
4      47  White        Married       T2      N1       IIB   
...   ...    ...            ...      ...     ...       ...   
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0         Poorly differentiated     3  Regional           4        Positive   
1     Moderately differentiated     2  Regional          35        Positive   
2     Moderately differentiated     2  Regional          63        Positive   
3         Poorly differentiated     3  Regional          18        Positive   
4         Poorly differentiated     3  Regional          41        Positive   
...                         ...   ...       ...         ...             ...   
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0               Positive                      24                      1   
1               Positive                      14                      5   
2               Positive                      14                      7   
3               Positive                       2                      1   
4               Positive                       3                      1   
...                  ...                     ...                    ...   
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
0                  60  Alive  
1                  62  Alive  
2                  75  Alive  
3                  84  Alive  
4                  50  Alive  
...               ...    ...  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive  

[4024 rows x 16 columns]

In [3]:
df.head()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   
3   58  White        Married       T1      N1       IIA   
4   47  White        Married       T2      N1       IIB   

               differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated     3  Regional           4        Positive   
1  Moderately differentiated     2  Regional          35        Positive   
2  Moderately differentiated     2  Regional          63        Positive   
3      Poorly differentiated     3  Regional          18        Positive   
4      Poorly differentiated     3  Regional          41        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   
3            Positive                       2                      1   
4            Positive                       3                      1   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive  
3               84  Alive  
4               50  Alive

In [4]:
df.tail()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive

In [5]:
df.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='object')

In [6]:
df.dtypes

Age                        int64
Race                      object
Marital Status            object
T Stage                   object
N Stage                   object
6th Stage                 object
differentiate             object
Grade                     object
A Stage                   object
Tumor Size                 int64
Estrogen Status           object
Progesterone Status       object
Regional Node Examined     int64
Reginol Node Positive      int64
Survival Months            int64
Status                    object
dtype: object

In [7]:
df.isna().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [8]:
df.drop(['Race','Marital Status'],axis=1,inplace=True)

In [9]:
df

Age T Stage  N Stage 6th Stage              differentiate Grade  \
0      68       T1      N1       IIA      Poorly differentiated     3   
1      50       T2      N2      IIIA  Moderately differentiated     2   
2      58       T3      N3      IIIC  Moderately differentiated     2   
3      58       T1      N1       IIA      Poorly differentiated     3   
4      47       T2      N1       IIB      Poorly differentiated     3   
...   ...      ...     ...       ...                        ...   ...   
4019   62       T1      N1       IIA  Moderately differentiated     2   
4020   56       T2      N2      IIIA  Moderately differentiated     2   
4021   68       T2      N1       IIB  Moderately differentiated     2   
4022   58       T2      N1       IIB  Moderately differentiated     2   
4023   46       T2      N1       IIB  Moderately differentiated     2   

       A Stage  Tumor Size Estrogen Status Progesterone Status  \
0     Regional           4        Positive            Positive   
1     Regional          35        Positive            Positive   
2     Regional          63        Positive            Positive   
3     Regional          18        Positive            Positive   
4     Regional          41        Positive            Positive   
...        ...         ...             ...                 ...   
4019  Regional           9        Positive            Positive   
4020  Regional          46        Positive            Positive   
4021  Regional          22        Positive            Negative   
4022  Regional          44        Positive            Positive   
4023  Regional          30        Positive            Positive   

      Regional Node Examined  Reginol Node Positive  Survival Months Status  
0                         24                      1               60  Alive  
1                         14                      5               62  Alive  
2                         14                      7               75  Alive  
3                          2                      1               84  Alive  
4                          3                      1               50  Alive  
...                      ...                    ...              ...    ...  
4019                       1                      1               49  Alive  
4020                      14                      8               69  Alive  
4021                      11                      3               69  Alive  
4022                      11                      1               72  Alive  
4023                       7                      2              100  Alive  

[4024 rows x 14 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
feature=['T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Estrogen Status',
       'Progesterone Status']
for i in feature:
  df[i]=label.fit_transform(df[i])

In [11]:
x=df.iloc[:,:-1].values
x

array([[ 68,   0,   0, ...,  24,   1,  60],
       [ 50,   1,   1, ...,  14,   5,  62],
       [ 58,   2,   2, ...,  14,   7,  75],
       ...,
       [ 68,   1,   0, ...,  11,   3,  69],
       [ 58,   1,   0, ...,  11,   1,  72],
       [ 46,   1,   0, ...,   7,   2, 100]])

In [12]:
y=df.iloc[:,-1].values
y

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Alive'],
      dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[ 67,   0,   0, ...,   2,   1,  99],
       [ 50,   0,   0, ...,  18,   1,  69],
       [ 51,   0,   1, ...,  20,   4, 107],
       ...,
       [ 49,   2,   0, ...,  22,   1,  76],
       [ 68,   0,   0, ...,  26,   1,  72],
       [ 67,   1,   2, ...,  25,  17,  75]])

In [14]:
x_test

array([[50,  1,  1, ...,  9,  7, 69],
       [42,  2,  0, ..., 13,  2, 90],
       [53,  0,  0, ..., 12,  3, 94],
       ...,
       [68,  1,  1, ..., 25,  5, 48],
       [57,  0,  0, ..., 19,  2, 70],
       [64,  0,  0, ...,  2,  1, 68]])

In [15]:
y_test

array(['Dead', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Alive'],
      dtype=object)

In [16]:
y_train

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Alive'],
      dtype=object)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [18]:
x_train

array([[ 1.47216064, -1.02031614, -0.6310921 , ..., -1.52992397,
        -0.61146695,  1.20718255],
       [-0.42096194, -1.02031614, -0.6310921 , ...,  0.45923325,
        -0.61146695, -0.10012141],
       [-0.30960179, -1.02031614,  0.81728228, ...,  0.70787791,
        -0.03033602,  1.55579694],
       ...,
       [-0.53232209,  1.58695268, -0.6310921 , ...,  0.95652256,
        -0.61146695,  0.20491618],
       [ 1.58352079, -1.02031614, -0.6310921 , ...,  1.45381187,
        -0.61146695,  0.03060899],
       [ 1.47216064,  0.28331827,  2.26565665, ...,  1.32948954,
         2.48789798,  0.16133938]])

In [19]:
x_test

array([[-0.42096194,  0.28331827,  0.81728228, ..., -0.65966769,
         0.5507949 , -0.10012141],
       [-1.31184315,  1.58695268, -0.6310921 , ..., -0.16237838,
        -0.41775664,  0.81499136],
       [-0.08688148, -1.02031614, -0.6310921 , ..., -0.28670071,
        -0.22404633,  0.98929856],
       ...,
       [ 1.58352079,  0.28331827,  0.81728228, ...,  1.32948954,
         0.16337428, -1.01523418],
       [ 0.35855912, -1.02031614, -0.6310921 , ...,  0.58355558,
        -0.41775664, -0.05654461],
       [ 1.13808019, -1.02031614, -0.6310921 , ..., -1.52992397,
        -0.61146695, -0.14369821]])

In [20]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB()
model.fit(x_train,y_train)

BernoulliNB()

In [21]:
y_pred=model.predict(x_test)
y_pred

array(['Dead', 'Alive', 'Alive', ..., 'Dead', 'Alive', 'Alive'],
      dtype='<U5')

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc_score=accuracy_score(y_test,y_pred)
cm

array([[894, 146],
       [ 89,  79]])

In [23]:
acc_score

0.8054635761589404

In [24]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

       Alive       0.91      0.86      0.88      1040
        Dead       0.35      0.47      0.40       168

    accuracy                           0.81      1208
   macro avg       0.63      0.66      0.64      1208
weighted avg       0.83      0.81      0.82      1208

