In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Breast_Cancer.csv')
df

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0      68  White        Married       T1      N1       IIA   
1      50  White        Married       T2      N2      IIIA   
2      58  White       Divorced       T3      N3      IIIC   
3      58  White        Married       T1      N1       IIA   
4      47  White        Married       T2      N1       IIB   
...   ...    ...            ...      ...     ...       ...   
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0         Poorly differentiated     3  Regional           4        Positive   
1     Moderately differentiated     2  Regional          35        Positive   
2     Moderately differentiated     2  Regional          63        Positive   
3         Poorly differentiated     3  Regional          18        Positive   
4         Poorly differentiated     3  Regional          41        Positive   
...                         ...   ...       ...         ...             ...   
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0               Positive                      24                      1   
1               Positive                      14                      5   
2               Positive                      14                      7   
3               Positive                       2                      1   
4               Positive                       3                      1   
...                  ...                     ...                    ...   
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
0                  60  Alive  
1                  62  Alive  
2                  75  Alive  
3                  84  Alive  
4                  50  Alive  
...               ...    ...  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive  

[4024 rows x 16 columns]

In [2]:
df.head()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   
3   58  White        Married       T1      N1       IIA   
4   47  White        Married       T2      N1       IIB   

               differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated     3  Regional           4        Positive   
1  Moderately differentiated     2  Regional          35        Positive   
2  Moderately differentiated     2  Regional          63        Positive   
3      Poorly differentiated     3  Regional          18        Positive   
4      Poorly differentiated     3  Regional          41        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   
3            Positive                       2                      1   
4            Positive                       3                      1   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive  
3               84  Alive  
4               50  Alive

In [3]:
df.tail()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
4019   62  Other        Married       T1      N1       IIA   
4020   56  White       Divorced       T2      N2      IIIA   
4021   68  White        Married       T2      N1       IIB   
4022   58  Black       Divorced       T2      N1       IIB   
4023   46  White        Married       T2      N1       IIB   

                  differentiate Grade   A Stage  Tumor Size Estrogen Status  \
4019  Moderately differentiated     2  Regional           9        Positive   
4020  Moderately differentiated     2  Regional          46        Positive   
4021  Moderately differentiated     2  Regional          22        Positive   
4022  Moderately differentiated     2  Regional          44        Positive   
4023  Moderately differentiated     2  Regional          30        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
4019            Positive                       1                      1   
4020            Positive                      14                      8   
4021            Negative                      11                      3   
4022            Positive                      11                      1   
4023            Positive                       7                      2   

      Survival Months Status  
4019               49  Alive  
4020               69  Alive  
4021               69  Alive  
4022               72  Alive  
4023              100  Alive

In [4]:
df.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='object')

In [5]:
df.dtypes

Age                        int64
Race                      object
Marital Status            object
T Stage                   object
N Stage                   object
6th Stage                 object
differentiate             object
Grade                     object
A Stage                   object
Tumor Size                 int64
Estrogen Status           object
Progesterone Status       object
Regional Node Examined     int64
Reginol Node Positive      int64
Survival Months            int64
Status                    object
dtype: object

In [6]:
df.isna().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [7]:
df.drop(['Race','Marital Status'],axis=1,inplace=True)

In [8]:
df.columns

Index(['Age', 'T Stage ', 'N Stage', '6th Stage', 'differentiate', 'Grade',
       'A Stage', 'Tumor Size', 'Estrogen Status', 'Progesterone Status',
       'Regional Node Examined', 'Reginol Node Positive', 'Survival Months',
       'Status'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
feature=['T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Estrogen Status',
       'Progesterone Status']
for i in feature:
  df[i]=label.fit_transform(df[i])

In [11]:
x=df.iloc[:,:-1].values
x

array([[ 68,   0,   0, ...,  24,   1,  60],
       [ 50,   1,   1, ...,  14,   5,  62],
       [ 58,   2,   2, ...,  14,   7,  75],
       ...,
       [ 68,   1,   0, ...,  11,   3,  69],
       [ 58,   1,   0, ...,  11,   1,  72],
       [ 46,   1,   0, ...,   7,   2, 100]])

In [13]:
y=df.iloc[:,-1].values
y

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Alive'],
      dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[ 62,   0,   1, ...,  18,   6,  67],
       [ 55,   1,   2, ...,  13,  10,  53],
       [ 49,   0,   0, ...,   6,   1,  56],
       ...,
       [ 57,   1,   0, ...,  31,   2,  45],
       [ 48,   1,   0, ...,  27,   1, 102],
       [ 53,   1,   0, ...,  14,   2, 104]])

In [16]:
x_test

array([[45,  0,  0, ..., 24,  1, 80],
       [61,  0,  0, ...,  8,  1, 48],
       [61,  1,  1, ..., 32,  5, 61],
       ...,
       [68,  2,  0, ...,  2,  2, 68],
       [53,  0,  0, ...,  1,  1,  4],
       [61,  1,  0, ..., 12,  3, 40]])

In [17]:
y_train

array(['Alive', 'Alive', 'Alive', ..., 'Dead', 'Alive', 'Alive'],
      dtype=object)

In [18]:
y_test

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Dead'],
      dtype=object)

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [20]:
x_train

array([[0.82051282, 0.        , 0.5       , ..., 0.28333333, 0.11111111,
        0.61904762],
       [0.64102564, 0.33333333, 1.        , ..., 0.2       , 0.2       ,
        0.48571429],
       [0.48717949, 0.        , 0.        , ..., 0.08333333, 0.        ,
        0.51428571],
       ...,
       [0.69230769, 0.33333333, 0.        , ..., 0.5       , 0.02222222,
        0.40952381],
       [0.46153846, 0.33333333, 0.        , ..., 0.43333333, 0.        ,
        0.95238095],
       [0.58974359, 0.33333333, 0.        , ..., 0.21666667, 0.02222222,
        0.97142857]])

In [21]:
x_test

array([[0.38461538, 0.        , 0.        , ..., 0.38333333, 0.        ,
        0.74285714],
       [0.79487179, 0.        , 0.        , ..., 0.11666667, 0.        ,
        0.43809524],
       [0.79487179, 0.33333333, 0.5       , ..., 0.51666667, 0.08888889,
        0.56190476],
       ...,
       [0.97435897, 0.66666667, 0.        , ..., 0.01666667, 0.02222222,
        0.62857143],
       [0.58974359, 0.        , 0.        , ..., 0.        , 0.        ,
        0.01904762],
       [0.79487179, 0.33333333, 0.        , ..., 0.18333333, 0.04444444,
        0.36190476]])

In [22]:
from sklearn.neighbors import KNeighborsClassifier
model1=KNeighborsClassifier(n_neighbors=7)
model1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [23]:
y_pred=model1.predict(x_test)
y_pred

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Dead', 'Alive'],
      dtype=object)

In [24]:
y_test

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Dead'],
      dtype=object)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1014,   19],
       [ 117,   58]])

In [26]:
score=accuracy_score(y_test,y_pred)
score

0.8874172185430463

In [27]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

       Alive       0.90      0.98      0.94      1033
        Dead       0.75      0.33      0.46       175

    accuracy                           0.89      1208
   macro avg       0.82      0.66      0.70      1208
weighted avg       0.88      0.89      0.87      1208



In [28]:
from sklearn.naive_bayes import MultinomialNB
model2=MultinomialNB()
model2.fit(x_train,y_train)

MultinomialNB()

In [29]:
y_pred=model2.predict(x_test)
y_pred

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Alive'],
      dtype='<U5')

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc_score=accuracy_score(y_test,y_pred)
cm

array([[1033,    0],
       [ 164,   11]])

In [31]:
acc_score

0.8642384105960265

In [32]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

       Alive       0.86      1.00      0.93      1033
        Dead       1.00      0.06      0.12       175

    accuracy                           0.86      1208
   macro avg       0.93      0.53      0.52      1208
weighted avg       0.88      0.86      0.81      1208



In [33]:
from sklearn.svm import SVC
model3=SVC()
model3.fit(x_train,y_train)

SVC()

In [34]:
y_pred=model3.predict(x_test)
y_pred

array(['Alive', 'Alive', 'Alive', ..., 'Alive', 'Alive', 'Alive'],
      dtype=object)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc_score=accuracy_score(y_test,y_pred)
cm

array([[1024,    9],
       [ 116,   59]])