In [1]:
# Drive mount : when we are uploading data from drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os   # Define path of file and directory
from sklearn.svm import SVC
from skimage.io import imread # used for reading images
from sklearn.model_selection import train_test_split
from skimage.transform import resize # The images should be of same size, so it is used to resize images
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [3]:
# To list the contents in a directory
os.listdir('/content/drive/MyDrive/Data-20241230T070359Z-001/Data')

['Cat', 'Dog']

In [4]:
os.listdir('/content/drive/MyDrive/Data-20241230T070359Z-001/Data/Dog')

['dog.61.jpg',
 'dog.68.jpg',
 'dog.4.jpg',
 'dog.38.jpg',
 'dog.59.jpg',
 'dog.34.jpg',
 'dog.67.jpg',
 'dog.63.jpg',
 'dog.47.jpg',
 'dog.8.jpg',
 'dog.6.jpg',
 'dog.50.jpg',
 'dog.36.jpg',
 'dog.42.jpg',
 'dog.55.jpg',
 'dog.65.jpg',
 'dog.9.jpg',
 'dog.62.jpg',
 'dog.39.jpg',
 'dog.64.jpg',
 'dog.43.jpg',
 'dog.66.jpg',
 'dog.56.jpg',
 'dog.45.jpg',
 'dog.57.jpg',
 'dog.58.jpg',
 'dog.51.jpg',
 'dog.44.jpg',
 'dog.29.jpg',
 'dog.3.jpg',
 'dog.7.jpg',
 'dog.33.jpg',
 'dog.18.jpg',
 'dog.35.jpg',
 'dog.25.jpg',
 'dog.37.jpg',
 'dog.31.jpg',
 'dog.26.jpg',
 'dog.12.jpg',
 'dog.1.jpg',
 'dog.16.jpg',
 'dog.17.jpg',
 'dog.40.jpg',
 'dog.28.jpg',
 'dog.48.jpg',
 'dog.30.jpg',
 'dog.15.jpg',
 'dog.22.jpg',
 'dog.32.jpg',
 'dog.27.jpg',
 'dog.19.jpg',
 'dog.10.jpg',
 'dog.2.jpg',
 'dog.52.jpg',
 'dog.13.jpg',
 'dog.46.jpg',
 'dog.20.jpg',
 'dog.41.jpg',
 'dog.14.jpg',
 'dog.21.jpg',
 'dog.54.jpg',
 'dog.49.jpg',
 'dog.24.jpg',
 'dog.53.jpg',
 'dog.5.jpg',
 'dog.23.jpg',
 'dog.11.jpg',
 'do

In [5]:
os.listdir('/content/drive/MyDrive/Data-20241230T070359Z-001/Data/Cat')

['cat.91.jpg',
 'cat.69.jpg',
 'cat.68.jpg',
 'cat.77.jpg',
 'cat.81.jpg',
 'cat.89.jpg',
 'cat.82.jpg',
 'cat.83.jpg',
 'cat.90.jpg',
 'cat.64.jpg',
 'cat.70.jpg',
 'cat.88.jpg',
 'cat.76.jpg',
 'cat.98.jpg',
 'cat.80.jpg',
 'cat.79.jpg',
 'cat.85.jpg',
 'cat.92.jpg',
 'cat.52.jpg',
 'cat.74.jpg',
 'cat.57.jpg',
 'cat.51.jpg',
 'cat.96.jpg',
 'cat.72.jpg',
 'cat.56.jpg',
 'cat.46.jpg',
 'cat.71.jpg',
 'cat.93.jpg',
 'cat.65.jpg',
 'cat.73.jpg',
 'cat.86.jpg',
 'cat.62.jpg',
 'cat.50.jpg',
 'cat.94.jpg',
 'cat.84.jpg',
 'cat.95.jpg',
 'cat.67.jpg',
 'cat.61.jpg',
 'cat.87.jpg',
 'cat.97.jpg',
 'cat.63.jpg',
 'cat.35.jpg',
 'cat.75.jpg',
 'cat.59.jpg',
 'cat.78.jpg',
 'cat.99.jpg',
 'cat.36.jpg',
 'cat.43.jpg',
 'cat.112.jpg',
 'cat.47.jpg',
 'cat.45.jpg',
 'cat.101.jpg',
 'cat.44.jpg',
 'cat.53.jpg',
 'cat.115.jpg',
 'cat.48.jpg',
 'cat.114.jpg',
 'cat.107.jpg',
 'cat.106.jpg',
 'cat.38.jpg',
 'cat.100.jpg',
 'cat.54.jpg',
 'cat.105.jpg',
 'cat.110.jpg',
 'cat.66.jpg',
 'cat.102.jpg',


In [6]:
len(os.listdir('/content/drive/MyDrive/Data-20241230T070359Z-001/Data/Cat'))

85

In [7]:
len(os.listdir('/content/drive/MyDrive/Data-20241230T070359Z-001/Data/Dog'))

68

In [8]:
# Join the path of cat : to explain join operation
# we can do this by simply copying the path of folder cat
catpath = os.path.join('/content/drive/MyDrive/Data-20241230T070359Z-001/Data','Cat') # joining
for img in os.listdir(catpath):
  print(img)

cat.91.jpg
cat.69.jpg
cat.68.jpg
cat.77.jpg
cat.81.jpg
cat.89.jpg
cat.82.jpg
cat.83.jpg
cat.90.jpg
cat.64.jpg
cat.70.jpg
cat.88.jpg
cat.76.jpg
cat.98.jpg
cat.80.jpg
cat.79.jpg
cat.85.jpg
cat.92.jpg
cat.52.jpg
cat.74.jpg
cat.57.jpg
cat.51.jpg
cat.96.jpg
cat.72.jpg
cat.56.jpg
cat.46.jpg
cat.71.jpg
cat.93.jpg
cat.65.jpg
cat.73.jpg
cat.86.jpg
cat.62.jpg
cat.50.jpg
cat.94.jpg
cat.84.jpg
cat.95.jpg
cat.67.jpg
cat.61.jpg
cat.87.jpg
cat.97.jpg
cat.63.jpg
cat.35.jpg
cat.75.jpg
cat.59.jpg
cat.78.jpg
cat.99.jpg
cat.36.jpg
cat.43.jpg
cat.112.jpg
cat.47.jpg
cat.45.jpg
cat.101.jpg
cat.44.jpg
cat.53.jpg
cat.115.jpg
cat.48.jpg
cat.114.jpg
cat.107.jpg
cat.106.jpg
cat.38.jpg
cat.100.jpg
cat.54.jpg
cat.105.jpg
cat.110.jpg
cat.66.jpg
cat.102.jpg
cat.119.jpg
cat.58.jpg
cat.117.jpg
cat.118.jpg
cat.41.jpg
cat.113.jpg
cat.111.jpg
cat.39.jpg
cat.60.jpg
cat.42.jpg
cat.37.jpg
cat.104.jpg
cat.116.jpg
cat.55.jpg
cat.109.jpg
cat.103.jpg
cat.108.jpg
cat.49.jpg
cat.40.jpg


In [9]:
dogpath = os.path.join('/content/drive/MyDrive/Data-20241230T070359Z-001/Data','Dog')
for img in os.listdir(dogpath):
  print(img)

dog.61.jpg
dog.68.jpg
dog.4.jpg
dog.38.jpg
dog.59.jpg
dog.34.jpg
dog.67.jpg
dog.63.jpg
dog.47.jpg
dog.8.jpg
dog.6.jpg
dog.50.jpg
dog.36.jpg
dog.42.jpg
dog.55.jpg
dog.65.jpg
dog.9.jpg
dog.62.jpg
dog.39.jpg
dog.64.jpg
dog.43.jpg
dog.66.jpg
dog.56.jpg
dog.45.jpg
dog.57.jpg
dog.58.jpg
dog.51.jpg
dog.44.jpg
dog.29.jpg
dog.3.jpg
dog.7.jpg
dog.33.jpg
dog.18.jpg
dog.35.jpg
dog.25.jpg
dog.37.jpg
dog.31.jpg
dog.26.jpg
dog.12.jpg
dog.1.jpg
dog.16.jpg
dog.17.jpg
dog.40.jpg
dog.28.jpg
dog.48.jpg
dog.30.jpg
dog.15.jpg
dog.22.jpg
dog.32.jpg
dog.27.jpg
dog.19.jpg
dog.10.jpg
dog.2.jpg
dog.52.jpg
dog.13.jpg
dog.46.jpg
dog.20.jpg
dog.41.jpg
dog.14.jpg
dog.21.jpg
dog.54.jpg
dog.49.jpg
dog.24.jpg
dog.53.jpg
dog.5.jpg
dog.23.jpg
dog.11.jpg
dog.60.jpg


In [10]:
flat_data_arr = []           # To collect input samples
target_arr = []              # To collect output samples
categories = ['Cat','Dog']   #
datadir = '/content/drive/MyDrive/Data-20241230T070359Z-001/Data'

In [11]:
for i in categories:       # first cat then dog
  print("Loading categories..........") # just to know it is loading we print a msg
  path = os.path.join(datadir,i)  # /content/drive/MyDrive/Data-20241230T070359Z-001/Data,Cat
  for img in os.listdir(path):
    img_arr = imread(os.path.join(path,img))
    img_resize = resize(img_arr,(150,150,3)) # std size, 150x150x3 columns, 150->height, 150->width, 3->RGB color format
    flat_data_arr.append(img_resize.flatten()) # to convert to linear(1D)
    target_arr.append(categories.index(i)) # cat - 0 , dog - 1 , indexes
  print("Loaded completely",i)

Loading categories..........
Loaded completely Cat
Loading categories..........
Loaded completely Dog


In [12]:
flat_data = np.array(flat_data_arr) # converting into array
target_data = np.array(target_arr)

df = pd.DataFrame(flat_data)
df.shape

(153, 67500)

In [13]:
df['Target'] = target_data
df.shape

(153, 67501)

In [14]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
print(x)
print(y)

        0         1         2         3         4         5         6      \
0    0.538843  0.523055  0.478061  0.527895  0.509120  0.483026  0.651962   
1    0.152891  0.160734  0.141126  0.157203  0.165046  0.145439  0.161832   
2    0.977146  0.988911  0.922244  0.967490  0.979254  0.912588  0.955543   
3    0.090196  0.027451  0.031373  0.090196  0.027451  0.031373  0.090196   
4    0.058648  0.058648  0.090021  0.063648  0.063648  0.095021  0.050579   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.192608  0.251432  0.278776  0.200281  0.259104  0.286449  0.174399   
149  0.458653  0.507357  0.442993  0.767779  0.813413  0.764808  0.833987   
150  0.848785  0.825256  0.778197  0.853138  0.829609  0.782550  0.859961   
151  0.551169  0.594946  0.526358  0.443540  0.487318  0.418729  0.426418   
152  0.450904  0.541100  0.509728  0.439668  0.529864  0.498491  0.436718   

        7         8         9      ...     67490     67491     67492  \
0  

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)
x_train.shape

(122, 67500)

In [35]:
x_test.shape

(31, 67500)

In [36]:
y_test.shape

(31,)

In [37]:
y_train.shape

(122,)

In [38]:
model = SVC()
model.fit(x_train,y_train)

SVC()

In [39]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0])

In [40]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[17,  0],
       [12,  2]])

In [41]:
acc_score = accuracy_score(y_test,y_pred)
acc_score

0.6129032258064516

In [42]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.59      1.00      0.74        17
           1       1.00      0.14      0.25        14

    accuracy                           0.61        31
   macro avg       0.79      0.57      0.49        31
weighted avg       0.77      0.61      0.52        31



In [43]:
path1 = '/content/drive/MyDrive/FELV-cat.jpg'
img = imread(path1)
img = resize(img,(150,150,3)).flatten().reshape(1,-1)   # model.predict([[]]), we used to pass 2D as i/p ie given as (1,-1)
model.predict(img)
# array([1]) means predicted as dog

array([1])

In [44]:
path2 = '/content/drive/MyDrive/dog_img.jpeg'
img = imread(path2)
img = resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])