In [40]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/mountains_vs_beaches_preferences.csv')
df

Age      Gender  Income Education_Level  Travel_Frequency  \
0       56        male   71477        bachelor                 9   
1       69        male   88740          master                 1   
2       46      female   46562          master                 0   
3       32  non-binary   99044     high school                 6   
4       60      female  106583     high school                 5   
...    ...         ...     ...             ...               ...   
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0                   skiing             2477     urban                     175   
1                 swimming             4777  suburban                     228   
2                   skiing             1469     urban                      71   
3                   hiking             1482     rural                      31   
4               sunbathing              516  suburban                      23   
...                    ...              ...       ...                     ...   
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                       267          summer     0                       1   
1                       190            fall     0                       1   
2                       280          winter     0                       0   
3                       255          summer     1                       0   
4                       151          winter     1                       1   
...                     ...             ...   ...                     ...   
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
0               1  
1               0  
2               1  
3               1  
4               0  
...           ...  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0  

[52444 rows x 14 columns]

In [41]:
df.head()

Age      Gender  Income Education_Level  Travel_Frequency  \
0   56        male   71477        bachelor                 9   
1   69        male   88740          master                 1   
2   46      female   46562          master                 0   
3   32  non-binary   99044     high school                 6   
4   60      female  106583     high school                 5   

  Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0               skiing             2477     urban                     175   
1             swimming             4777  suburban                     228   
2               skiing             1469     urban                      71   
3               hiking             1482     rural                      31   
4           sunbathing              516  suburban                      23   

   Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                   267          summer     0                       1   
1                   190            fall     0                       1   
2                   280          winter     0                       0   
3                   255          summer     1                       0   
4                   151          winter     1                       1   

   Preference  
0           1  
1           0  
2           1  
3           1  
4           0

In [42]:
df.tail()

Age      Gender  Income Education_Level  Travel_Frequency  \
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0

In [43]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education_Level', 'Travel_Frequency',
       'Preferred_Activities', 'Vacation_Budget', 'Location',
       'Proximity_to_Mountains', 'Proximity_to_Beaches', 'Favorite_Season',
       'Pets', 'Environmental_Concerns', 'Preference'],
      dtype='object')

In [44]:
df.isna().sum()

Age                       0
Gender                    0
Income                    0
Education_Level           0
Travel_Frequency          0
Preferred_Activities      0
Vacation_Budget           0
Location                  0
Proximity_to_Mountains    0
Proximity_to_Beaches      0
Favorite_Season           0
Pets                      0
Environmental_Concerns    0
Preference                0
dtype: int64

In [45]:
df.drop('Education_Level',axis=1,inplace=True)

In [46]:
df.dtypes

Age                        int64
Gender                    object
Income                     int64
Travel_Frequency           int64
Preferred_Activities      object
Vacation_Budget            int64
Location                  object
Proximity_to_Mountains     int64
Proximity_to_Beaches       int64
Favorite_Season           object
Pets                       int64
Environmental_Concerns     int64
Preference                 int64
dtype: object

In [47]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
feature=['Gender', 'Preferred_Activities', 'Location','Favorite_Season']
for i in feature:
  df[i]=label.fit_transform(df[i])

In [48]:
x=df.iloc[:,:-1].values
x

array([[   56,     1, 71477, ...,     2,     0,     1],
       [   69,     1, 88740, ...,     0,     0,     1],
       [   46,     0, 46562, ...,     3,     0,     0],
       ...,
       [   53,     2, 71080, ...,     0,     0,     1],
       [   40,     0, 75174, ...,     2,     0,     1],
       [   33,     2, 34475, ...,     1,     1,     0]])

In [49]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, ..., 0, 0, 0])

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[    49,      0,  69367, ...,      1,      0,      0],
       [    50,      2, 103956, ...,      3,      1,      1],
       [    30,      1,  91462, ...,      2,      1,      1],
       ...,
       [    63,      0,  68714, ...,      1,      0,      1],
       [    20,      2,  30887, ...,      3,      1,      0],
       [    38,      2,  78821, ...,      2,      0,      1]])

In [51]:
x_test

array([[   39,     0, 64201, ...,     1,     1,     1],
       [   21,     0, 36359, ...,     1,     1,     1],
       [   41,     0, 45354, ...,     1,     1,     0],
       ...,
       [   26,     2, 83005, ...,     2,     0,     1],
       [   34,     1, 40751, ...,     1,     1,     1],
       [   27,     1, 89989, ...,     1,     0,     1]])

In [52]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [53]:
y_test

array([0, 0, 1, ..., 1, 0, 0])

In [54]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [55]:
x_train

array([[ 0.36806641, -1.21996839, -0.02431588, ..., -0.44609984,
        -1.00010897, -0.99478342],
       [ 0.43480809,  1.23717037,  1.17020435, ...,  1.34014854,
         0.99989104,  1.00524393],
       [-0.90002536,  0.00860099,  0.73872799, ...,  0.44702435,
         0.99989104,  1.00524393],
       ...,
       [ 1.30244983, -1.21996839, -0.04686703, ..., -0.44609984,
        -1.00010897,  1.00524393],
       [-1.56744208,  1.23717037, -1.35321056, ...,  1.34014854,
         0.99989104, -0.99478342],
       [-0.36609198,  1.23717037,  0.30217504, ...,  0.44702435,
        -1.00010897,  1.00524393]])

In [56]:
x_test

array([[-0.29935031, -1.21996839, -0.20272206, ..., -0.44609984,
         0.99989104,  1.00524393],
       [-1.50070041, -1.21996839, -1.16423676, ..., -0.44609984,
         0.99989104,  1.00524393],
       [-0.16586696, -1.21996839, -0.85359727, ..., -0.44609984,
         0.99989104, -0.99478342],
       ...,
       [-1.16699205,  1.23717037,  0.44666816, ...,  0.44702435,
        -1.00010897,  1.00524393],
       [-0.63305867,  0.00860099, -1.01256043, ..., -0.44609984,
         0.99989104,  1.00524393],
       [-1.10025038,  0.00860099,  0.6878584 , ..., -0.44609984,
        -1.00010897,  1.00524393]])

In [57]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
knn=KNeighborsClassifier()
BNB=BernoulliNB()
sv=SVC()
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
lst=[knn,BNB,sv]

In [58]:
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("Model is : ",i)
  print(y_pred)
  print("Confusion Matrix : ")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy Score : ")
  print(accuracy_score(y_test,y_pred))
  print("Classifiacation Report : ")
  print(classification_report(y_test,y_pred))
  print("*"*100)

Model is :  KNeighborsClassifier()
[0 0 1 ... 1 0 0]
Confusion Matrix : 
[[11423   425]
 [  665  3221]]
Accuracy Score : 
0.9307232744375238
Classifiacation Report : 
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     11848
           1       0.88      0.83      0.86      3886

    accuracy                           0.93     15734
   macro avg       0.91      0.90      0.90     15734
weighted avg       0.93      0.93      0.93     15734

****************************************************************************************************
Model is :  BernoulliNB()
[0 0 0 ... 1 0 0]
Confusion Matrix : 
[[11848     0]
 [ 1919  1967]]
Accuracy Score : 
0.8780348290326682
Classifiacation Report : 
              precision    recall  f1-score   support

           0       0.86      1.00      0.93     11848
           1       1.00      0.51      0.67      3886

    accuracy                           0.88     15734
   macro avg       0.93      