In [1]:
import numpy as np
import pandas as pd
outlook=['sunny','sunny','overcast','rainy','rainy','rainy','overcast','sunny','sunny','rainy','sunny','overcast','overcast','rainy']

temperature=['hot','hot','hot','mild','cool','cool','cool','mild','cool','mild','mild','mild','hot','mild']

humidity=['high','high','high','high','normal','normal','normal','high','normal','normal','normal','high','normal','high']

wind=['weak','strong','weak','weak','weak','strong','strong','weak','weak','weak','strong','strong','weak','strong']

play=['no','no','yes','yes','yes','no','yes','no','yes','yes','yes','yes','yes','no']

convert the object dtype into numerical dtype, output whether numerical or object not an issue
Encoding
1. Label Encoding
2. OneHot Encoding
3. Get_dummies

In [2]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
outlook_encoder=label.fit_transform(outlook)
outlook_encoder

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [3]:
temp_encoder=label.fit_transform(temperature)
temp_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [4]:
humidity_encoder=label.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [5]:
wind_encoder=label.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [8]:
# combine all these lists into one list
feature=list(zip(outlook_encoder,temp_encoder,humidity_encoder,wind_encoder))
feature

[(2, 1, 0, 1),
 (2, 1, 0, 0),
 (0, 1, 0, 1),
 (1, 2, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 0),
 (0, 0, 1, 0),
 (2, 2, 0, 1),
 (2, 0, 1, 1),
 (1, 2, 1, 1),
 (2, 2, 1, 0),
 (0, 2, 0, 0),
 (0, 1, 1, 1),
 (1, 2, 0, 0)]

No need to split the data into training and testing bcz only 10 datas
creating model
3 types of classifiers can use to create naive bayes model
1. Gaussian     : If the data is continuous (only numerical datas)
2. Multinomial  : If the data is Discrete (contains object datas)
3. Bernoulli    : Can use both for continuous and discrete

In [9]:
# Here we use multinomial classifier. Because it contains object (discrete) data
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(feature,play)

MultinomialNB()

In [10]:
# predicting whether can play tennis or not using values X=(Outlook=Sunny, Temp=Cool, Humidity=High, Wind=Strong)
# X = (2,0,0,0)
print(model.predict([[2,0,0,0]]))

['no']
