In [29]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/lung_cancer_examples.csv')
df

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [30]:
df.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [31]:
df.tail()

Name   Surname  Age  Smokes  AreaQ  Alkhol  Result
54    Ernest   Borgnine   26      13      6       1       0
55      Alec   Guinness   77      20      5       4       1
56  Charlton     Heston   75      15      3       5       1
57   Gregory       Peck   43      30      3       8       1
58    Sidney    Poitier   51      25      9       0       0

In [32]:
df.columns

Index(['Name', 'Surname', 'Age', 'Smokes', 'AreaQ', 'Alkhol', 'Result'], dtype='object')

In [33]:
df.dtypes

Name       object
Surname    object
Age         int64
Smokes      int64
AreaQ       int64
Alkhol      int64
Result      int64
dtype: object

In [34]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [35]:
df.drop(['Name','Surname'],axis=1,inplace=True)

In [36]:
df.dtypes

Age       int64
Smokes    int64
AreaQ     int64
Alkhol    int64
Result    int64
dtype: object

In [37]:
x=df.iloc[:,:-1].values
x

array([[35,  3,  5,  4],
       [27, 20,  2,  5],
       [30,  0,  5,  2],
       [28,  0,  8,  1],
       [68,  4,  5,  6],
       [34,  0, 10,  0],
       [58, 15, 10,  0],
       [22, 12,  5,  2],
       [45,  2,  6,  0],
       [52, 18,  4,  5],
       [33,  4,  8,  0],
       [18, 10,  6,  3],
       [25,  2,  5,  1],
       [28, 20,  2,  8],
       [34, 25,  4,  8],
       [39, 18,  8,  1],
       [42, 22,  3,  5],
       [19, 12,  8,  0],
       [62,  5,  4,  3],
       [73, 10,  7,  6],
       [55, 15,  1,  3],
       [33,  8,  8,  1],
       [22, 20,  6,  2],
       [44,  5,  8,  1],
       [77,  3,  2,  6],
       [21, 20,  5,  3],
       [37, 15,  6,  2],
       [34, 12,  8,  0],
       [55, 20,  1,  4],
       [40, 20,  2,  7],
       [36, 13,  5,  2],
       [56, 20,  3,  3],
       [47, 15,  1,  8],
       [62, 25,  3,  4],
       [26, 10,  7,  2],
       [25, 20,  8,  2],
       [59, 20,  3,  4],
       [62, 15,  5,  5],
       [33, 25,  8,  2],
       [37, 10,  5,  3],


In [38]:
y=df.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[26, 13,  6,  1],
       [73, 10,  7,  6],
       [36, 13,  5,  2],
       [42, 12,  6,  2],
       [39, 15,  7,  2],
       [77, 20,  5,  4],
       [39, 18,  8,  1],
       [52, 18,  4,  5],
       [34, 12,  8,  0],
       [37, 15,  6,  2],
       [42, 22,  3,  5],
       [77,  3,  2,  6],
       [62, 25,  3,  4],
       [75, 15,  3,  5],
       [47, 12,  8,  0],
       [18, 10,  6,  3],
       [47, 15,  1,  8],
       [26, 34,  1,  8],
       [50, 20,  2,  4],
       [62, 15,  5,  5],
       [40, 20,  2,  7],
       [63, 20,  4,  5],
       [27, 20,  2,  5],
       [33,  8,  8,  1],
       [30,  0,  5,  2],
       [31, 20,  9,  4],
       [37, 10,  5,  3],
       [25, 20,  8,  2],
       [44,  5,  8,  1],
       [53, 20,  6,  3],
       [33,  4,  8,  0],
       [22, 20,  6,  2],
       [62,  5,  4,  3],
       [51, 25,  9,  0],
       [55, 15,  1,  3],
       [22, 12,  5,  2],
       [69, 20,  5,  4],
       [34, 25,  4,  8],
       [55, 20,  1,  4],
       [44, 30,  1,  6],


In [40]:
x_test

array([[35,  3,  5,  4],
       [34,  0, 10,  0],
       [26, 10,  7,  2],
       [28, 20,  2,  8],
       [21, 20,  8,  3],
       [35, 20,  5,  1],
       [43, 30,  3,  8],
       [21, 20,  5,  3],
       [28, 10,  4,  1],
       [25,  2,  5,  1],
       [62, 20,  5,  6],
       [28,  0,  8,  1],
       [59, 20,  3,  4],
       [56, 20,  3,  3],
       [45,  2,  6,  0],
       [19, 12,  8,  0],
       [58, 15, 10,  0],
       [68,  4,  5,  6]])

In [41]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [42]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [43]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [44]:
x_train

array([[0.13559322, 0.38235294, 0.625     , 0.125     ],
       [0.93220339, 0.29411765, 0.75      , 0.75      ],
       [0.30508475, 0.38235294, 0.5       , 0.25      ],
       [0.40677966, 0.35294118, 0.625     , 0.25      ],
       [0.3559322 , 0.44117647, 0.75      , 0.25      ],
       [1.        , 0.58823529, 0.5       , 0.5       ],
       [0.3559322 , 0.52941176, 0.875     , 0.125     ],
       [0.57627119, 0.52941176, 0.375     , 0.625     ],
       [0.27118644, 0.35294118, 0.875     , 0.        ],
       [0.3220339 , 0.44117647, 0.625     , 0.25      ],
       [0.40677966, 0.64705882, 0.25      , 0.625     ],
       [1.        , 0.08823529, 0.125     , 0.75      ],
       [0.74576271, 0.73529412, 0.25      , 0.5       ],
       [0.96610169, 0.44117647, 0.25      , 0.625     ],
       [0.49152542, 0.35294118, 0.875     , 0.        ],
       [0.        , 0.29411765, 0.625     , 0.375     ],
       [0.49152542, 0.44117647, 0.        , 1.        ],
       [0.13559322, 1.        ,

In [45]:
x_test

array([[0.28813559, 0.08823529, 0.5       , 0.5       ],
       [0.27118644, 0.        , 1.125     , 0.        ],
       [0.13559322, 0.29411765, 0.75      , 0.25      ],
       [0.16949153, 0.58823529, 0.125     , 1.        ],
       [0.05084746, 0.58823529, 0.875     , 0.375     ],
       [0.28813559, 0.58823529, 0.5       , 0.125     ],
       [0.42372881, 0.88235294, 0.25      , 1.        ],
       [0.05084746, 0.58823529, 0.5       , 0.375     ],
       [0.16949153, 0.29411765, 0.375     , 0.125     ],
       [0.11864407, 0.05882353, 0.5       , 0.125     ],
       [0.74576271, 0.58823529, 0.5       , 0.75      ],
       [0.16949153, 0.        , 0.875     , 0.125     ],
       [0.69491525, 0.58823529, 0.25      , 0.5       ],
       [0.6440678 , 0.58823529, 0.25      , 0.375     ],
       [0.45762712, 0.05882353, 0.625     , 0.        ],
       [0.01694915, 0.35294118, 0.875     , 0.        ],
       [0.6779661 , 0.44117647, 1.125     , 0.        ],
       [0.84745763, 0.11764706,

In [46]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [47]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [48]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
acc_score=accuracy_score(y_test,y_pred)
cm

array([[11,  0],
       [ 1,  6]])

[TN FP]

[FN TP]

This is in this format

array ([[11,  0],

       [ 1,  6]])

Not in the usual format

In [49]:
acc_score

0.9444444444444444